spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true
  freemarker:
    enabled: true
    suffix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false


server:
  port: 53021
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    context-path: /order
  tomcat:
    remoteip:
      host-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  forward-headers-strategy: framework
logging:
  level:
    root: debug
    org:
      springframework: info
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, env
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:53000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
